// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeu8iQocxeF7wnS2Ls4opzSUmA64pDAPc',
    appId: '1:410182745546:web:34f72264a3e0acb0cde333',
    messagingSenderId: '410182745546',
    projectId: 'travel-buddy-app-ff589',
    authDomain: 'travel-buddy-app-ff589.firebaseapp.com',
    storageBucket: 'travel-buddy-app-ff589.firebasestorage.app',
    measurementId: 'G-03PQQ3DC6Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCe2xiXd1WU_nwOmigjFaOaPF8A2yI4tc',
    appId: '1:410182745546:android:a4aa3807359ad8dacde333',
    messagingSenderId: '410182745546',
    projectId: 'travel-buddy-app-ff589',
    storageBucket: 'travel-buddy-app-ff589.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJQEZISDve7tltuo_MMqx_DQ2q4gqSHqI',
    appId: '1:410182745546:ios:0e28332bb618a713cde333',
    messagingSenderId: '410182745546',
    projectId: 'travel-buddy-app-ff589',
    storageBucket: 'travel-buddy-app-ff589.firebasestorage.app',
    iosBundleId: 'com.example.travelBuddy',
  );
}
